// <auto-generated />
using System;
using DevInCar.API.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevInCar.API.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221020192315_addUserSeeds")]
    partial class addUserSeeds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DevInCar.API.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            EmailAddress = "yan@devinhouse.com",
                            Name = "Yan",
                            Password = "yan123"
                        },
                        new
                        {
                            Id = "2",
                            EmailAddress = "admin@devinhouse.com",
                            Name = "Administrador",
                            Password = "admin"
                        });
                });

            modelBuilder.Entity("DevInCar.API.Models.Vehicle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BuyerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChassisNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoorsNumber")
                        .HasColumnType("int");

                    b.Property<int>("FuelType")
                        .HasColumnType("int");

                    b.Property<int?>("LoadingCapacity")
                        .HasColumnType("int");

                    b.Property<string>("ManufacturingDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("Potency")
                        .HasColumnType("float");

                    b.Property<string>("SaleDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.Property<int>("WheelsNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = "cr_ea939f06-3e4a-4f4e-a993-cf4448124007",
                            ChassisNumber = "c4fdb597-a901-4895-a1f9-dedb6653b48c",
                            Color = "Prata",
                            DoorsNumber = 4,
                            FuelType = 3,
                            ManufacturingDate = "01-01-2013",
                            Name = "Punto",
                            PlateNumber = "XPT-0000",
                            Potency = 130.0,
                            SaleDate = "",
                            Status = true,
                            Value = 38000.0,
                            VehicleType = 3,
                            WheelsNumber = 4
                        },
                        new
                        {
                            Id = "cr_6ab4d679-e859-48d5-b45c-c22496d44b5d",
                            ChassisNumber = "2b0246ca-c0ab-4b49-9d1a-80a47c836b11",
                            Color = "Preto",
                            DoorsNumber = 4,
                            FuelType = 3,
                            ManufacturingDate = "01-01-2018",
                            Name = "Prisma",
                            PlateNumber = "XPT-1111",
                            Potency = 180.0,
                            SaleDate = "",
                            Status = true,
                            Value = 42000.0,
                            VehicleType = 3,
                            WheelsNumber = 4
                        },
                        new
                        {
                            Id = "cr_f2c559bd-bcc5-4d87-8b39-35c06efd7ff2",
                            ChassisNumber = "0cf5a60c-bb8b-4278-b370-a7187dd766d9",
                            Color = "Branco",
                            DoorsNumber = 4,
                            FuelType = 3,
                            ManufacturingDate = "01-01-2022",
                            Name = "Creta",
                            PlateNumber = "XPT-2222",
                            Potency = 130.0,
                            SaleDate = "",
                            Status = true,
                            Value = 150000.0,
                            VehicleType = 3,
                            WheelsNumber = 4
                        },
                        new
                        {
                            Id = "mt_6d2d9657-4070-4f88-82ed-ea15e676e36d",
                            ChassisNumber = "d064a8a6-ab14-4866-9380-a75749b01f42",
                            Color = "Branca",
                            FuelType = 1,
                            ManufacturingDate = "01-01-2020",
                            Name = "CG Titan",
                            PlateNumber = "TOP-0666",
                            Potency = 180.0,
                            SaleDate = "",
                            Status = true,
                            Value = 13000.0,
                            VehicleType = 1,
                            WheelsNumber = 2
                        },
                        new
                        {
                            Id = "mt_6c9a7aac-e106-40f9-8d3a-9e5e3aeb7ec6",
                            ChassisNumber = "7b602007-5089-495d-8334-c01bffa2b7cf",
                            Color = "Branca",
                            FuelType = 1,
                            ManufacturingDate = "01-01-2020",
                            Name = "Fazer",
                            PlateNumber = "TOP-0777",
                            Potency = 180.0,
                            SaleDate = "",
                            Status = true,
                            Value = 13000.0,
                            VehicleType = 1,
                            WheelsNumber = 2
                        },
                        new
                        {
                            Id = "mt_223e1d0e-a875-4cc2-acba-dab628f8ca9f",
                            ChassisNumber = "721d0393-6f3c-47ff-a427-e1448c2fff5e",
                            Color = "Vinho",
                            FuelType = 1,
                            ManufacturingDate = "01-01-1994",
                            Name = "750 Four",
                            PlateNumber = "TOP-0999",
                            Potency = 750.0,
                            SaleDate = "",
                            Status = true,
                            Value = 42000.0,
                            VehicleType = 1,
                            WheelsNumber = 2
                        },
                        new
                        {
                            Id = "tk_286ff6a1-4fbf-4575-979c-1775850b6d74",
                            ChassisNumber = "bb36f3b7-e364-425d-b212-77dbf8347e36",
                            Color = "Preto",
                            DoorsNumber = 4,
                            FuelType = 2,
                            LoadingCapacity = 1000,
                            ManufacturingDate = "01-01-2018",
                            Name = "Hilux",
                            PlateNumber = "ABC-1234",
                            Potency = 450.0,
                            SaleDate = "",
                            Status = true,
                            Value = 80000.0,
                            VehicleType = 4,
                            WheelsNumber = 4
                        },
                        new
                        {
                            Id = "tk_f79cb0e4-398e-4be8-87ae-453e0ba1cedc",
                            ChassisNumber = "bbdaf98f-d45b-452f-a565-5a44a368c039",
                            Color = "Preto",
                            DoorsNumber = 4,
                            FuelType = 2,
                            LoadingCapacity = 2500,
                            ManufacturingDate = "01-01-2009",
                            Name = "F1000",
                            PlateNumber = "ABC-4323",
                            Potency = 800.0,
                            SaleDate = "",
                            Status = true,
                            Value = 70000.0,
                            VehicleType = 4,
                            WheelsNumber = 4
                        },
                        new
                        {
                            Id = "tk_4d32a3f7-fe49-4b91-9516-8f00ca6f1d77",
                            ChassisNumber = "47130c42-db9c-4350-8d2a-08a500538f8c",
                            Color = "Preto",
                            DoorsNumber = 4,
                            FuelType = 1,
                            LoadingCapacity = 2500,
                            ManufacturingDate = "01-01-2012",
                            Name = "Montana",
                            PlateNumber = "ABC-4341",
                            Potency = 250.0,
                            SaleDate = "",
                            Status = true,
                            Value = 35000.0,
                            VehicleType = 4,
                            WheelsNumber = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
